'use client';

import { useState, useCallback, useRef, useEffect, forwardRef } from 'react';
import { Byoky } from '@byoky/sdk';
import type { ByokySession } from '@byoky/sdk';
import { startDeviceFlow, pollForToken, getUser, createRepo, pushFiles } from './github';
import type { GitHubUser, RepoInfo } from './github';
import { generateApp } from './generator';
import type { GenerateResult, Message } from './generator';
import { TEMPLATES } from './templates';
import './dev.css';

/* ─── Helpers ──────────────────────────────────── */

function sanitizeRepoName(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'my-app';
}

async function downloadZip(files: Record<string, string>, name: string): Promise<void> {
  const JSZip = (await import('jszip')).default;
  const zip = new JSZip();
  for (const [path, content] of Object.entries(files)) {
    zip.file(path, content.replaceAll('{{PROJECT_NAME}}', name));
  }
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${name}.zip`;
  a.click();
  URL.revokeObjectURL(url);
}

async function openInStackBlitz(files: Record<string, string>, name: string): Promise<void> {
  const sdk = await import('@stackblitz/sdk');
  const processed: Record<string, string> = {};
  for (const [path, content] of Object.entries(files)) {
    processed[path] = content.replaceAll('{{PROJECT_NAME}}', name);
  }
  sdk.default.openProject({
    title: name,
    description: 'Generated by Byoky App Generator',
    template: 'node',
    files: processed,
  }, { openFile: 'src/app/page.tsx' });
}

/* ─── Main Component ──────────────────────────── */

export default function DevHub() {
  /* ── Connection state ── */
  const [walletSession, setWalletSession] = useState<ByokySession | null>(null);
  const [walletConnecting, setWalletConnecting] = useState(false);
  const [githubToken, setGithubToken] = useState<string | null>(null);
  const [githubUser, setGithubUser] = useState<GitHubUser | null>(null);
  const [deviceFlow, setDeviceFlow] = useState<{
    user_code: string;
    verification_uri: string;
  } | null>(null);

  /* ── Chat & Generation state ── */
  const [messages, setMessages] = useState<Array<{ role: 'user' | 'assistant'; content: string }>>([]);
  const [generating, setGenerating] = useState(false);
  const [generatedFiles, setGeneratedFiles] = useState<Record<string, string> | null>(null);
  const [activeFile, setActiveFile] = useState<string | null>(null);

  /* ── Deploy state ── */
  const [repoName, setRepoName] = useState('');
  const [isPrivate, setIsPrivate] = useState(false);
  const [pushing, setPushing] = useState(false);
  const [pushProgress, setPushProgress] = useState<{ done: number; total: number } | null>(null);
  const [result, setResult] = useState<RepoInfo | null>(null);

  /* ── UI state ── */
  const [error, setError] = useState<string | null>(null);
  const [mode, setMode] = useState<'chat' | 'template'>('chat');
  const [showRepoInput, setShowRepoInput] = useState(false);

  /* ── Refs ── */
  const abortRef = useRef<AbortController | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const errorTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  /* ── Auto-focus textarea on mount ── */
  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  /* ── Auto-scroll chat to bottom ── */
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, generating]);

  /* ── Auto-dismiss error after 5s ── */
  useEffect(() => {
    if (!error) return;
    if (errorTimerRef.current) clearTimeout(errorTimerRef.current);
    errorTimerRef.current = setTimeout(() => setError(null), 5000);
    return () => {
      if (errorTimerRef.current) clearTimeout(errorTimerRef.current);
    };
  }, [error]);

  /* ── Derived ── */
  const connectedProviders = walletSession
    ? Object.entries(walletSession.providers)
        .filter(([, v]) => v.available)
        .map(([k]) => k)
    : [];

  const filePaths = generatedFiles ? Object.keys(generatedFiles).sort() : [];
  const hasMessages = messages.length > 0;

  /* ─── Wallet connect ────────────────────────── */

  const connectWallet = useCallback(async () => {
    setWalletConnecting(true);
    setError(null);
    try {
      const byoky = new Byoky();
      const session = await byoky.connect({
        providers: [
          { id: 'anthropic', required: false },
          { id: 'openai', required: false },
          { id: 'gemini', required: false },
        ],
        modal: true,
      });
      setWalletSession(session);
    } catch (e) {
      if (e instanceof Error && e.message.includes('cancelled')) return;
      setError(e instanceof Error ? e.message : 'Failed to connect wallet');
    } finally {
      setWalletConnecting(false);
    }
  }, []);

  const disconnectWallet = useCallback(() => {
    walletSession?.disconnect();
    setWalletSession(null);
  }, [walletSession]);

  /* ─── GitHub connect (device flow) ──────────── */

  const connectGitHub = useCallback(async () => {
    setError(null);
    try {
      const flow = await startDeviceFlow();
      setDeviceFlow({
        user_code: flow.user_code,
        verification_uri: flow.verification_uri,
      });
      window.open(flow.verification_uri, '_blank');

      const controller = new AbortController();
      abortRef.current = controller;

      const token = await pollForToken(flow.device_code, flow.interval, controller.signal);
      setGithubToken(token);

      const user = await getUser(token);
      setGithubUser(user);
    } catch (e) {
      if (e instanceof DOMException && e.name === 'AbortError') return;
      setError(e instanceof Error ? e.message : 'GitHub auth failed');
    } finally {
      setDeviceFlow(null);
      abortRef.current = null;
    }
  }, []);

  const cancelDeviceFlow = useCallback(() => {
    abortRef.current?.abort();
    setDeviceFlow(null);
  }, []);

  const disconnectGitHub = useCallback(() => {
    setGithubToken(null);
    setGithubUser(null);
    setResult(null);
  }, []);

  /* ─── Send chat message (generate/refine) ──── */

  const [inputValue, setInputValue] = useState('');

  const handleSend = useCallback(async () => {
    if (!walletSession || !inputValue.trim() || generating) return;

    const userText = inputValue.trim();
    setInputValue('');
    setGenerating(true);
    setError(null);
    setResult(null);

    const isFirst = messages.length === 0;
    const updatedMessages: Message[] = [...messages, { role: 'user', content: userText }];
    setMessages(updatedMessages);

    try {
      const proxyFetch = walletSession.createFetch('anthropic');
      const previousMessages: Message[] = isFirst ? [] : messages;
      const res: GenerateResult = await generateApp(proxyFetch, userText, previousMessages.length > 0 ? previousMessages : undefined);

      if (isFirst) {
        setGeneratedFiles(res.files);
        setRepoName(sanitizeRepoName(userText.split(/\s+/).slice(0, 4).join('-')));
      } else {
        setGeneratedFiles((prev) => ({ ...prev, ...res.files }));
      }

      const changedFiles = Object.keys(res.files).sort();
      if (changedFiles.length > 0) {
        setActiveFile(changedFiles[0]);
      }

      setMessages([...updatedMessages, { role: 'assistant', content: res.description }]);
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Generation failed';
      if (msg.includes('SESSION_EXPIRED') || msg.includes('expired session')) {
        setError('Session expired — reconnecting...');
        setWalletSession(null);
        try {
          const byoky = new Byoky();
          const session = await byoky.connect({
            providers: [
              { id: 'anthropic', required: false },
              { id: 'openai', required: false },
              { id: 'gemini', required: false },
            ],
            modal: true,
          });
          setWalletSession(session);
          setError(null);
        } catch {
          setError('Session expired. Please reconnect your wallet.');
        }
      } else {
        setError(msg);
      }
      setMessages(updatedMessages);
    } finally {
      setGenerating(false);
    }
  }, [walletSession, inputValue, generating, messages]);

  /* ─── Template selection ────────────────────── */

  const selectTemplate = useCallback((id: string) => {
    const template = TEMPLATES.find((t) => t.id === id);
    if (!template) return;

    setGeneratedFiles(template.files);
    const firstFile = Object.keys(template.files).sort()[0] ?? null;
    setActiveFile(firstFile);
    setRepoName(`my-${id}`);
    setResult(null);
    setError(null);
    setMode('chat');

    setMessages([
      { role: 'user', content: `I want to use the ${template.name} template` },
      { role: 'assistant', content: `Here's your ${template.name} app. The files are ready \u2014 check the code panel.` },
    ]);
  }, []);

  /* ─── Push to GitHub ────────────────────────── */

  const handlePush = useCallback(async () => {
    if (!githubToken || !githubUser || !generatedFiles || !repoName.trim()) return;

    setPushing(true);
    setPushProgress(null);
    setError(null);
    setResult(null);

    try {
      const repo = await createRepo(githubToken, repoName.trim(), isPrivate);

      const processedFiles: Record<string, string> = {};
      for (const [path, content] of Object.entries(generatedFiles)) {
        processedFiles[path] = content.replaceAll('{{PROJECT_NAME}}', repoName.trim());
      }

      await pushFiles(
        githubToken,
        githubUser.login,
        repoName.trim(),
        processedFiles,
        (done, total) => setPushProgress({ done, total }),
      );

      setResult(repo);
      setShowRepoInput(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to push to GitHub');
    } finally {
      setPushing(false);
      setPushProgress(null);
    }
  }, [githubToken, githubUser, generatedFiles, repoName, isPrivate]);

  /* ─── Keyboard shortcuts ────────────────────── */

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        handleSend();
      }
    },
    [handleSend],
  );

  /* ─── Render helpers ────────────────────────── */

  const renderCodeLines = (content: string) => {
    return content.split('\n').map((line, i) => (
      <span key={i} className="dh-code-line">{line}</span>
    ));
  };

  /* ─── Render ────────────────────────────────── */

  return (
    <div className="dh-container">
      {/* ── Top Bar ── */}
      <div className="dh-topbar">
        <div className="dh-topbar-left">
          <a href="/" className="dh-brand">Byoky</a>
          <span className="dh-topbar-title">App Generator</span>
        </div>
        <div className="dh-topbar-right">
          {/* Wallet pill */}
          {walletSession ? (
            <button className="dh-pill dh-pill-connected" onClick={disconnectWallet}>
              <span className="dh-dot dh-dot-green" />
              {connectedProviders.length} provider{connectedProviders.length !== 1 ? 's' : ''}
            </button>
          ) : (
            <button className="dh-pill" onClick={connectWallet} disabled={walletConnecting}>
              {walletConnecting ? (
                <><span className="dh-spinner-sm" /> Connecting...</>
              ) : (
                'Connect Wallet'
              )}
            </button>
          )}

          {/* GitHub pill */}
          {githubUser ? (
            <button className="dh-pill dh-pill-connected" onClick={disconnectGitHub}>
              <span className="dh-dot dh-dot-green" />
              {githubUser.login}
            </button>
          ) : deviceFlow ? (
            <div className="dh-device-inline">
              <code className="dh-device-code-sm">{deviceFlow.user_code}</code>
              <span className="dh-spinner-sm" />
              <button className="dh-link-btn" onClick={cancelDeviceFlow}>Cancel</button>
            </div>
          ) : (
            <button className="dh-pill" onClick={connectGitHub}>
              <GitHubIcon /> Connect GitHub
            </button>
          )}

          {/* Export actions */}
          {generatedFiles && (
            <div className="dh-export-actions">
              <button
                className="dh-export-btn"
                onClick={() => downloadZip(generatedFiles, repoName || 'my-app').catch(e => setError(e.message))}
                title="Download as ZIP"
              >
                <DownloadIcon /> ZIP
              </button>
              <button
                className="dh-export-btn"
                onClick={() => openInStackBlitz(generatedFiles, repoName || 'my-app').catch(e => setError(e.message))}
                title="Open in StackBlitz"
              >
                <StackBlitzIcon /> StackBlitz
              </button>
              {githubUser && (
                <>
                  {result ? (
                    <a
                      href={result.html_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="dh-export-btn dh-export-btn-success"
                    >
                      View Repo &#8599;
                    </a>
                  ) : showRepoInput ? (
                    <div className="dh-repo-inline">
                      <input
                        className="dh-repo-input"
                        type="text"
                        value={repoName}
                        onChange={(e) => setRepoName(e.target.value)}
                        placeholder="repo-name"
                        disabled={pushing}
                      />
                      <label className="dh-repo-private">
                        <input
                          type="checkbox"
                          checked={isPrivate}
                          onChange={(e) => setIsPrivate(e.target.checked)}
                          disabled={pushing}
                        />
                        Private
                      </label>
                      <button
                        className="dh-export-btn dh-export-btn-primary"
                        onClick={handlePush}
                        disabled={pushing || !repoName.trim()}
                      >
                        {pushing ? <><span className="dh-spinner-sm" /> Pushing...</> : 'Push'}
                      </button>
                    </div>
                  ) : (
                    <button
                      className="dh-export-btn dh-export-btn-primary"
                      onClick={() => setShowRepoInput(true)}
                    >
                      <GitHubIcon /> Push
                    </button>
                  )}
                </>
              )}
            </div>
          )}
        </div>
      </div>

      {/* ── Push progress bar ── */}
      {pushing && pushProgress && (
        <div className="dh-push-progress">
          <div
            className="dh-push-progress-fill"
            style={{ width: `${(pushProgress.done / pushProgress.total) * 100}%` }}
          />
        </div>
      )}

      {/* ── Split Layout ── */}
      <div className="dh-split">
        {/* ── Chat Panel (left) ── */}
        <div className="dh-chat-panel">
          {mode === 'template' ? (
            /* Template picker */
            <div className="dh-template-view">
              <button className="dh-template-back" onClick={() => setMode('chat')}>
                &larr; Back to chat
              </button>
              <div className="dh-template-grid">
                {TEMPLATES.map((t) => (
                  <TemplateCard key={t.id} template={t} onSelect={selectTemplate} />
                ))}
              </div>
            </div>
          ) : !hasMessages && !generating ? (
            /* Empty state */
            <>
              <div className="dh-chat-empty">
                <div className="dh-chat-empty-icon">
                  <WalletIcon />
                </div>
                <h3>What do you want to build?</h3>
                <p>Describe your app and we will generate the code using your AI keys.</p>
              </div>
              <ChatInput
                ref={textareaRef}
                value={inputValue}
                onChange={setInputValue}
                onSend={handleSend}
                onKeyDown={handleKeyDown}
                disabled={!walletSession || generating}
                walletConnected={!!walletSession}
                walletConnecting={walletConnecting}
                onConnectWallet={connectWallet}
                placeholder="Describe your app..."
                onTemplatesClick={() => setMode('template')}
              />
            </>
          ) : (
            /* Messages view */
            <>
              <div className="dh-chat-messages">
                {messages.map((msg, i) => (
                  <div key={i} className={`dh-msg dh-msg-${msg.role}`}>
                    <span className="dh-msg-label">
                      {msg.role === 'user' ? 'you' : 'Byoky'}
                    </span>
                    <div className="dh-msg-bubble">{msg.content}</div>
                  </div>
                ))}
                {generating && (
                  <div className="dh-msg dh-msg-assistant">
                    <span className="dh-msg-label">Byoky</span>
                    <div className="dh-typing">
                      <span className="dh-typing-dot" />
                      <span className="dh-typing-dot" />
                      <span className="dh-typing-dot" />
                    </div>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>
              <ChatInput
                ref={textareaRef}
                value={inputValue}
                onChange={setInputValue}
                onSend={handleSend}
                onKeyDown={handleKeyDown}
                disabled={!walletSession || generating}
                walletConnected={!!walletSession}
                walletConnecting={walletConnecting}
                onConnectWallet={connectWallet}
                placeholder="What would you like to change?"
                onTemplatesClick={() => setMode('template')}
              />
            </>
          )}
        </div>

        {/* ── Code Panel (right) ── */}
        <div className="dh-code-panel">
          {generating && !generatedFiles ? (
            /* Generating state (first generation) */
            <div className="dh-code-generating">
              <div className="dh-gen-pulse" />
              <p>Building your idea...</p>
            </div>
          ) : generatedFiles && filePaths.length > 0 ? (
            /* Files view */
            <>
              <div className="dh-file-tabs">
                {filePaths.map((fp) => (
                  <button
                    key={fp}
                    className={`dh-file-tab${activeFile === fp ? ' dh-file-tab-active' : ''}`}
                    onClick={() => setActiveFile(fp)}
                  >
                    {fp}
                  </button>
                ))}
              </div>
              <div className="dh-code-area">
                {activeFile && generatedFiles[activeFile] !== undefined ? (
                  <pre className="dh-code-block">
                    <code>{renderCodeLines(generatedFiles[activeFile])}</code>
                  </pre>
                ) : (
                  <div className="dh-code-empty">
                    <p>Select a file to preview</p>
                  </div>
                )}
              </div>
            </>
          ) : (
            /* Empty state */
            <div className="dh-code-empty">
              <div className="dh-code-empty-icon">
                <CodeIcon />
              </div>
              <p>Your app will appear here</p>
            </div>
          )}
        </div>
      </div>

      {/* ── Error Toast ── */}
      {error && (
        <div className="dh-toast">
          <span>{error}</span>
          <button className="dh-toast-dismiss" onClick={() => setError(null)}>
            &times;
          </button>
        </div>
      )}
    </div>
  );
}

/* ─── Chat Input Component ─────────────────────── */

interface ChatInputProps {
  value: string;
  onChange: (v: string) => void;
  onSend: () => void;
  onKeyDown: (e: React.KeyboardEvent) => void;
  disabled: boolean;
  walletConnected: boolean;
  walletConnecting: boolean;
  onConnectWallet: () => void;
  placeholder: string;
  onTemplatesClick: () => void;
}

const ChatInput = forwardRef<HTMLTextAreaElement, ChatInputProps>(
  function ChatInput({ value, onChange, onSend, onKeyDown, disabled, walletConnected, walletConnecting, onConnectWallet, placeholder, onTemplatesClick }, ref) {
    if (!walletConnected) {
      return (
        <div className="dh-chat-input-area">
          <button
            className="dh-connect-btn"
            onClick={onConnectWallet}
            disabled={walletConnecting}
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 12V7H5a2 2 0 0 1 0-4h14v4" />
              <path d="M3 5v14a2 2 0 0 0 2 2h16v-5" />
              <path d="M18 12a2 2 0 0 0 0 4h4v-4z" />
            </svg>
            {walletConnecting ? 'Connecting...' : 'Connect Wallet to Start'}
          </button>
          <div className="dh-chat-footer">
            <button className="dh-templates-link" onClick={onTemplatesClick}>
              or use a template
            </button>
          </div>
        </div>
      );
    }

    return (
      <div className="dh-chat-input-area">
        <div className="dh-chat-input-wrap">
          <textarea
            ref={ref}
            className="dh-chat-textarea"
            rows={2}
            value={value}
            onChange={(e) => onChange(e.target.value)}
            onKeyDown={onKeyDown}
            placeholder={placeholder}
            disabled={disabled}
          />
          <button
            className="dh-chat-send"
            onClick={onSend}
            disabled={disabled || !value.trim()}
            aria-label="Send message"
          >
            <ArrowIcon />
          </button>
        </div>
        <div className="dh-chat-footer">
          <button className="dh-templates-link" onClick={onTemplatesClick}>
            Templates
          </button>
        </div>
      </div>
    );
  },
);

/* ─── Template Card ────────────────────────────── */

function TemplateCard({
  template,
  onSelect,
}: {
  template: { id: string; name: string; description: string; tech: string; color: string };
  onSelect: (id: string) => void;
}) {
  const techTags = template.tech.split(' \u00b7 ');

  return (
    <div
      className="dh-template-card"
      onClick={() => onSelect(template.id)}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(template.id);
        }
      }}
    >
      <div
        className="dh-template-icon"
        style={{ background: `${template.color}15`, color: template.color }}
      >
        {template.name.charAt(0)}
      </div>
      <h3>{template.name}</h3>
      <p>{template.description}</p>
      <div className="dh-template-tags">
        {techTags.map((tag) => (
          <span key={tag} className="dh-template-tag">{tag}</span>
        ))}
      </div>
    </div>
  );
}

/* ─── Icons ────────────────────────────────────── */

function WalletIcon() {
  return (
    <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 12V7H5a2 2 0 0 1 0-4h14v4" />
      <path d="M3 5v14a2 2 0 0 0 2 2h16v-5" />
      <path d="M18 12a2 2 0 0 0 0 4h4v-4z" />
    </svg>
  );
}

function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  );
}

function StackBlitzIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
      <path d="M10.797 14.182H3.635L16.728 0l-3.525 9.818h7.162L7.272 24l3.525-9.818z" />
    </svg>
  );
}

function GitHubIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
      <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
    </svg>
  );
}

function ArrowIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="5" y1="12" x2="19" y2="12" />
      <polyline points="12 5 19 12 12 19" />
    </svg>
  );
}

function CodeIcon() {
  return (
    <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" opacity="0.3">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}
